//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Script1.rc
//
#define IDR_MAINMENU                    101
#define IDR_ACCELERATOR1                102
#define IDD_DIALOG1                     103
#define IDD_GOTODIALOG                  103
#define IDD_DIALOG2                     104
#define IDD_FINDDIALOG                  104
#define IDI_ICON1                       105
#define IDD_DIALOG3                     107
#define IDD_ABOUTDIALOG                 107
#define IDD_DIALOG4                     112
#define IDD_HEXDUMPDIALOG               112
#define IDD_DIALOG5                     115
#define IDD_DECIMALDIALOG               115
#define IDD_PASTEDIALOG                 116
#define IDD_CUTDIALOG                   117
#define IDD_COPYDIALOG                  118
#define IDD_VIEWSETTINGSDIALOG          119
#define IDD_APPENDDIALOG                123
#define IDD_MANIPBITSDIALOG             124
#define IDD_CHARACTERSETDIALOG          125
#define IDD_CHOOSEDIFFDIALOG            126
#define IDD_BINARYMODEDIALOG            127
#define IDD_SELECT_BLOCK_DIALOG         128
#define IDD_ADDBMK_DIALOG               129
#define IDD_REMOVEBMK_DIALOG            130
#define IDD_OPEN_PARTIAL_DIALOG         131
#define IDD_FASTPASTE_DIALOG            132
#define IDD_TMPL_RESULT_DIALOG          133
#define IDD_REPLACEDIALOG               134
#define IDD_FILL_WITH                   135
#define IDC_EDIT1                       1000
#define IDC_CHECK1                      1001
#define IDC_REPLACEWITH_EDIT            1001
#define IDC_RADIO1                      1002
#define IDC_CHECK2                      1002
#define IDC_RADIO2                      1003
#define IDC_CHECK3                      1003
#define IDC_EDIT2                       1004
#define IDC_CHECK4                      1004
#define IDC_AND                         1004
#define IDC_RADIO3                      1005
#define IDC_CHECK5                      1005
#define IDC_ES                          1005
#define IDC_CHECK6                      1006
#define IDC_SS                          1006
#define IDC_CHECK7                      1007
#define IDC_SI                          1007
#define IDC_EDIT3                       1008
#define IDC_CHECK8                      1008
#define IDC_IFS                         1008
#define IDC_EDIT4                       1009
#define IDC_R                           1009
#define IDC_XOR                         1010
#define IDC_STATIC1                     1013
#define IDC_LIST1                       1014
#define IDC_STATIC2                     1015
#define IDC_BUTTON1                     1018
#define IDC_FINDNEXT_BUTTON             1020
#define IDC_TYPE                        1020
#define IDC_FINDPREVIOUS_BUTTON         1021
#define IDC_BROWSE                      1021
#define IDC_MATCHCASE_CHECK             1022
#define IDC_FN                          1022
#define IDC_REPLACE_BUTTON              1023
#define IDC_HEXSTAT                     1023
#define IDC_FOLLOCC_BUTTON              1024
#define IDC_PREVOCC_BUTTON              1025
#define IDC_STS                         1025
#define IDC_TO_REPLACE_EDIT             1026
#define IDC_USETRANSLATION_CHECK        1027
#define IDCOPY                          1028
#define IDC_HEX                         1046
#define IDC_FILESTAT                    1047
#define IDC_EQ                          1048
#define IDC_OR                          1049
#define IDM_OPEN                        40002
#define IDM_NEW                         40003
#define IDM_TOP                         40004
#define IDM_BOTTOM                      40005
#define IDM_SCROLL_LEFT                 40007
#define IDM_SCROLL_RIGHT                40008
#define IDM_SCROLL_UP                   40009
#define IDM_SCROLL_DOWN                 40010
#define IDM_SAVE                        40011
#define IDM_SAVE_AS                     40012
#define IDM_EXIT                        40013
#define IDM_CHANGE_MODE                 40014
#define IDM_FIND                        40015
#define IDM_GO_TO                       40016
#define IDM_ABOUT                       40017
#define IDM_EDIT_COPY                   40021
#define IDM_EDIT_PASTE                  40022
#define IDM_COPY_HEXDUMP                40023
#define IDM_EDIT_ENTERDECIMALVALUE      40025
#define IDM_HELP_TOPICS                 40026
#define IDM_EDIT_CUT                    40027
#define IDM_INTERNALSTATUS              40028
#define IDA_SELECTRIGHT                 40029
#define IDA_SELECTLEFT                  40030
#define IDA_SELECTUP                    40031
#define IDA_SELECTDOWN                  40032
#define IDA_SELECTENDOFLINE             40033
#define IDA_SELECTSTARTOFLINE           40034
#define IDA_SELECTSTARTOFFILE           40035
#define IDA_SELECTENDOFFILE             40036
#define IDM_VIEW_SETTINGS               40037
#define IDM_TEXT_COLOR                  40039
#define IDM_BK_COLOR                    40040
#define IDM_EDIT_APPEND                 40045
#define IDM_EDIT_MANIPULATEBITS         40046
#define IDM_CHARACTER_SET               40047
#define IDA_DELETEKEY                   40048
#define IDA_INSERTMODETOGGLE            40049
#define IDA_BACKSPACE                   40050
#define IDM_SELECT_ALL                  40051
#define IDM_PROPERTIES                  40052
#define IDM_READFLOAT                   40053
#define IDM_COMPARE                     40054
#define IDM_BINARYMODE                  40055
#define IDA_SELECTPAGEDOWN              40056
#define IDA_SELECTPAGEUP                40057
#define IDM_SELECT_BLOCK                40058
#define IDM_SEP_COLOR                   40064
#define IDM_ADDBOOKMARK                 40065
#define IDM_BOOKMARK1                   40066
#define IDM_BOOKMARK2                   40067
#define IDM_BOOKMARK3                   40068
#define IDM_BOOKMARK4                   40069
#define IDM_BOOKMARK5                   40070
#define IDM_BOOKMARK6                   40071
#define IDM_BOOKMARK7                   40072
#define IDM_BOOKMARK8                   40073
#define IDM_BOOKMARK9                   40074
#define IDM_REMOVE_BKM                  40077
#define IDM_CLEARALL_BMK                40078
#define IDM_PARTIAL_OPEN                40079
#define IDM_PASTE_WITH_DLG              40080
#define IDM_MRU1                        40081
#define IDM_MRU2                        40082
#define IDM_MRU3                        40083
#define IDM_MRU4                        40084
#define IDM_MRU5                        40085
#define IDM_MRU6                        40086
#define IDM_MRU7                        40087
#define IDM_MRU8                        40088
#define IDM_MRU9                        40089
#define IDM_APPLYTEMPLATE               40091
#define IDM_EDIT_READONLYMODE           40092
#define IDM_RESET_COLORS                40093
#define IDM_SELTEXT_COLOR               40094
#define IDM_SELBACK_COLOR               40095
#define IDM_BMK_COLOR                   40096
#define IDM_FINDNEXT                    40097
#define IDM_FINDPREV                    40098
#define IDM_OPEN_TEXT                   40099
#define IDM_EXPLORERSETTINGS            40100
#define IDM_REPLACE                     40101
#define IDM_FILL_WITH                   40102
#define IDM_SAVESELAS                   40103
#define IDM_REVERT                      40104
#define IDM_INSERTFILE                  40105
#define IDM_DELETEFILE                  40106

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40108
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
